include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml

variables:
  #TF_ROOT: "${CI_PROJECT_DIR}"
  TF_STATE_NAME: ${CI_COMMIT_BRANCH:-default}
  TF_HTTP_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}-cloud"
  TF_HTTP_LOCK_ADDRESS: "${TF_HTTP_ADDRESS}/lock"
  TF_HTTP_LOCK_METHOD: "POST"
  TF_HTTP_UNLOCK_ADDRESS: "${TF_HTTP_ADDRESS}/lock"
  TF_HTTP_UNLOCK_METHOD: "DELETE"
  TF_VAR_tf_access_token: ${CI_JOB_TOKEN}
  ENVIRONMENT: "PROD"

stages:
  - validate
  - test
  - build
  - deploy
  - fill_data
  - cleanup

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  extends: .terraform:build

deploy_cloud:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
  when: manual

destroy_cloud:
  extends: .terraform:destroy