#cloud-config
package_update: true
packages:
  - mc
  - postgresql-client
  - jq

write_files:
  - encoding: b64
    content: YC_CONFIG
    owner: ubuntu:ubuntu
    path: /home/ubuntu/.config/yandex-cloud/config.yaml
    defer: true
